2019-12-18 11:08:24,930 ERROR: Exception on /search [GET] [in /Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/routes.py", line 242, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/search.py", line 17, in query_index
    if not es:
NameError: name 'es' is not defined
2019-12-18 11:09:10,849 INFO: Microblog startup [in /Users/preciousemakenemi/Desktop/projects/microblog/app/_init_.py:62]
2019-12-18 11:09:13,807 ERROR: Exception on /search [GET] [in /Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/routes.py", line 242, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/search.py", line 19, in query_index
    search = app.elasticsearch.search(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 810, in search
    return self.transport.perform_request(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2019-12-18 11:09:33,265 ERROR: Exception on /search [GET] [in /Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/routes.py", line 242, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/search.py", line 19, in query_index
    search = app.elasticsearch.search(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 810, in search
    return self.transport.perform_request(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2019-12-18 11:10:08,324 ERROR: Exception on /search [GET] [in /Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/routes.py", line 242, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/preciousemakenemi/Desktop/projects/microblog/app/search.py", line 24, in query_index
    return ids, search,['hits']['total']['value']
TypeError: list indices must be integers or slices, not str
